<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../Quicker.Integration.TestSupport/Quicker.Integration.TestSupport.csproj" />
    <ProjectReference Include="../Quicker.Integration/Quicker.Integration.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Quicker.Observability/Quicker.Observability.csproj" />
    <ProjectReference Include="../../Identity/Quicker.Identity.TestSupport/Quicker.Identity.TestSupport.csproj" />
  </ItemGroup>

</Project>
