<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../Quicker.Numbering.TestSupport/Quicker.Numbering.TestSupport.csproj" />
    <ProjectReference Include="../Quicker.Numbering/Quicker.Numbering.csproj" />
    <ProjectReference Include="../../Identity/Quicker.Identity.TestSupport/Quicker.Identity.TestSupport.csproj" />
  </ItemGroup>

</Project>
