<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../Quicker.Organization.TestSupport/Quicker.Organization.TestSupport.csproj" />
    <ProjectReference Include="../Quicker.Organization/Quicker.Organization.csproj" />
    <ProjectReference Include="../../Identity/Quicker.Identity.TestSupport/Quicker.Identity.TestSupport.csproj" />
  </ItemGroup>

</Project>
