-- ISO 4217 currencies (A-008): platform reference data, idempotent. Minor units follow the ISO list;
-- companies override display precision and cash rounding in app.org_company_currencies.
INSERT INTO control.currencies (code, numeric_code, minor_units, symbol, name_i18n) VALUES
  ('AED', '784', 2, 'د.إ', '{"en":"UAE dirham","ar":"درهم إماراتي"}'),
  ('AFN', '971', 2, '؋', '{"en":"Afghan afghani","ar":"أفغاني"}'),
  ('ALL', '008', 2, 'L', '{"en":"Albanian lek","ar":"ليك ألباني"}'),
  ('AMD', '051', 2, '֏', '{"en":"Armenian dram","ar":"درام أرميني"}'),
  ('ANG', '532', 2, 'ƒ', '{"en":"Netherlands Antillean guilder","ar":"غيلدر أنتيلي هولندي"}'),
  ('AOA', '973', 2, 'Kz', '{"en":"Angolan kwanza","ar":"كوانزا أنغولي"}'),
  ('ARS', '032', 2, '$', '{"en":"Argentine peso","ar":"بيزو أرجنتيني"}'),
  ('AUD', '036', 2, 'A$', '{"en":"Australian dollar","ar":"دولار أسترالي"}'),
  ('AWG', '533', 2, 'ƒ', '{"en":"Aruban florin","ar":"فلورن أروبي"}'),
  ('AZN', '944', 2, '₼', '{"en":"Azerbaijani manat","ar":"مانات أذربيجاني"}'),
  ('BAM', '977', 2, 'KM', '{"en":"Bosnia and Herzegovina convertible mark","ar":"مارك بوسني قابل للتحويل"}'),
  ('BBD', '052', 2, '$', '{"en":"Barbados dollar","ar":"دولار بربادوسي"}'),
  ('BDT', '050', 2, '৳', '{"en":"Bangladeshi taka","ar":"تاكا بنغلاديشي"}'),
  ('BGN', '975', 2, 'лв', '{"en":"Bulgarian lev","ar":"ليف بلغاري"}'),
  ('BHD', '048', 3, 'د.ب', '{"en":"Bahraini dinar","ar":"دينار بحريني"}'),
  ('BIF', '108', 0, 'FBu', '{"en":"Burundian franc","ar":"فرنك بوروندي"}'),
  ('BMD', '060', 2, '$', '{"en":"Bermudian dollar","ar":"دولار برمودي"}'),
  ('BND', '096', 2, '$', '{"en":"Brunei dollar","ar":"دولار بروناي"}'),
  ('BOB', '068', 2, 'Bs.', '{"en":"Bolivian boliviano","ar":"بوليفيانو بوليفي"}'),
  ('BRL', '986', 2, 'R$', '{"en":"Brazilian real","ar":"ريال برازيلي"}'),
  ('BSD', '044', 2, '$', '{"en":"Bahamian dollar","ar":"دولار بهامي"}'),
  ('BTN', '064', 2, 'Nu.', '{"en":"Bhutanese ngultrum","ar":"نغولتروم بوتاني"}'),
  ('BWP', '072', 2, 'P', '{"en":"Botswana pula","ar":"بولا بوتسواني"}'),
  ('BYN', '933', 2, 'Br', '{"en":"Belarusian ruble","ar":"روبل بيلاروسي"}'),
  ('BZD', '084', 2, 'BZ$', '{"en":"Belize dollar","ar":"دولار بليزي"}'),
  ('CAD', '124', 2, 'C$', '{"en":"Canadian dollar","ar":"دولار كندي"}'),
  ('CDF', '976', 2, 'FC', '{"en":"Congolese franc","ar":"فرنك كونغولي"}'),
  ('CHF', '756', 2, 'CHF', '{"en":"Swiss franc","ar":"فرنك سويسري"}'),
  ('CLP', '152', 0, '$', '{"en":"Chilean peso","ar":"بيزو تشيلي"}'),
  ('CNY', '156', 2, '¥', '{"en":"Chinese yuan","ar":"يوان صيني"}'),
  ('COP', '170', 2, '$', '{"en":"Colombian peso","ar":"بيزو كولومبي"}'),
  ('CRC', '188', 2, '₡', '{"en":"Costa Rican colón","ar":"كولون كوستاريكي"}'),
  ('CUP', '192', 2, '$', '{"en":"Cuban peso","ar":"بيزو كوبي"}'),
  ('CVE', '132', 2, '$', '{"en":"Cape Verdean escudo","ar":"إسكودو الرأس الأخضر"}'),
  ('CZK', '203', 2, 'Kč', '{"en":"Czech koruna","ar":"كورونا تشيكية"}'),
  ('DJF', '262', 0, 'Fdj', '{"en":"Djiboutian franc","ar":"فرنك جيبوتي"}'),
  ('DKK', '208', 2, 'kr', '{"en":"Danish krone","ar":"كرونة دنماركية"}'),
  ('DOP', '214', 2, 'RD$', '{"en":"Dominican peso","ar":"بيزو دومينيكاني"}'),
  ('DZD', '012', 2, 'د.ج', '{"en":"Algerian dinar","ar":"دينار جزائري"}'),
  ('EGP', '818', 2, 'ج.م', '{"en":"Egyptian pound","ar":"جنيه مصري"}'),
  ('ERN', '232', 2, 'Nfk', '{"en":"Eritrean nakfa","ar":"ناكفا إريتري"}'),
  ('ETB', '230', 2, 'Br', '{"en":"Ethiopian birr","ar":"بير إثيوبي"}'),
  ('EUR', '978', 2, '€', '{"en":"Euro","ar":"يورو"}'),
  ('FJD', '242', 2, '$', '{"en":"Fijian dollar","ar":"دولار فيجي"}'),
  ('FKP', '238', 2, '£', '{"en":"Falkland Islands pound","ar":"جنيه جزر فوكلاند"}'),
  ('GBP', '826', 2, '£', '{"en":"Pound sterling","ar":"جنيه إسترليني"}'),
  ('GEL', '981', 2, '₾', '{"en":"Georgian lari","ar":"لاري جورجي"}'),
  ('GHS', '936', 2, '₵', '{"en":"Ghanaian cedi","ar":"سيدي غاني"}'),
  ('GIP', '292', 2, '£', '{"en":"Gibraltar pound","ar":"جنيه جبل طارق"}'),
  ('GMD', '270', 2, 'D', '{"en":"Gambian dalasi","ar":"دالاسي غامبي"}'),
  ('GNF', '324', 0, 'FG', '{"en":"Guinean franc","ar":"فرنك غيني"}'),
  ('GTQ', '320', 2, 'Q', '{"en":"Guatemalan quetzal","ar":"كتزال غواتيمالي"}'),
  ('GYD', '328', 2, '$', '{"en":"Guyanese dollar","ar":"دولار غياني"}'),
  ('HKD', '344', 2, 'HK$', '{"en":"Hong Kong dollar","ar":"دولار هونغ كونغ"}'),
  ('HNL', '340', 2, 'L', '{"en":"Honduran lempira","ar":"لمبيرا هندوراسي"}'),
  ('HTG', '332', 2, 'G', '{"en":"Haitian gourde","ar":"غورد هايتي"}'),
  ('HUF', '348', 2, 'Ft', '{"en":"Hungarian forint","ar":"فورنت مجري"}'),
  ('IDR', '360', 2, 'Rp', '{"en":"Indonesian rupiah","ar":"روبية إندونيسية"}'),
  ('ILS', '376', 2, '₪', '{"en":"Israeli new shekel","ar":"شيكل إسرائيلي جديد"}'),
  ('INR', '356', 2, '₹', '{"en":"Indian rupee","ar":"روبية هندية"}'),
  ('IQD', '368', 3, 'ع.د', '{"en":"Iraqi dinar","ar":"دينار عراقي"}'),
  ('IRR', '364', 2, '﷼', '{"en":"Iranian rial","ar":"ريال إيراني"}'),
  ('ISK', '352', 0, 'kr', '{"en":"Icelandic króna","ar":"كرونا آيسلندية"}'),
  ('JMD', '388', 2, 'J$', '{"en":"Jamaican dollar","ar":"دولار جامايكي"}'),
  ('JOD', '400', 3, 'د.أ', '{"en":"Jordanian dinar","ar":"دينار أردني"}'),
  ('JPY', '392', 0, '¥', '{"en":"Japanese yen","ar":"ين ياباني"}'),
  ('KES', '404', 2, 'KSh', '{"en":"Kenyan shilling","ar":"شلن كيني"}'),
  ('KGS', '417', 2, 'с', '{"en":"Kyrgyzstani som","ar":"سوم قيرغيزستاني"}'),
  ('KHR', '116', 2, '៛', '{"en":"Cambodian riel","ar":"ريال كمبودي"}'),
  ('KMF', '174', 0, 'CF', '{"en":"Comorian franc","ar":"فرنك قمري"}'),
  ('KPW', '408', 2, '₩', '{"en":"North Korean won","ar":"وون كوري شمالي"}'),
  ('KRW', '410', 0, '₩', '{"en":"South Korean won","ar":"وون كوري جنوبي"}'),
  ('KWD', '414', 3, 'د.ك', '{"en":"Kuwaiti dinar","ar":"دينار كويتي"}'),
  ('KYD', '136', 2, '$', '{"en":"Cayman Islands dollar","ar":"دولار جزر كايمان"}'),
  ('KZT', '398', 2, '₸', '{"en":"Kazakhstani tenge","ar":"تينغ كازاخستاني"}'),
  ('LAK', '418', 2, '₭', '{"en":"Lao kip","ar":"كيب لاوسي"}'),
  ('LBP', '422', 2, 'ل.ل', '{"en":"Lebanese pound","ar":"ليرة لبنانية"}'),
  ('LKR', '144', 2, 'Rs', '{"en":"Sri Lankan rupee","ar":"روبية سريلانكية"}'),
  ('LRD', '430', 2, '$', '{"en":"Liberian dollar","ar":"دولار ليبيري"}'),
  ('LSL', '426', 2, 'L', '{"en":"Lesotho loti","ar":"لوتي ليسوتو"}'),
  ('LYD', '434', 3, 'ل.د', '{"en":"Libyan dinar","ar":"دينار ليبي"}'),
  ('MAD', '504', 2, 'د.م.', '{"en":"Moroccan dirham","ar":"درهم مغربي"}'),
  ('MDL', '498', 2, 'L', '{"en":"Moldovan leu","ar":"ليو مولدوفي"}'),
  ('MGA', '969', 2, 'Ar', '{"en":"Malagasy ariary","ar":"أرياري مدغشقري"}'),
  ('MKD', '807', 2, 'ден', '{"en":"Macedonian denar","ar":"دينار مقدوني"}'),
  ('MMK', '104', 2, 'K', '{"en":"Myanmar kyat","ar":"كيات ميانماري"}'),
  ('MNT', '496', 2, '₮', '{"en":"Mongolian tögrög","ar":"توغروغ منغولي"}'),
  ('MOP', '446', 2, 'MOP$', '{"en":"Macanese pataca","ar":"باتاكا ماكاوية"}'),
  ('MRU', '929', 2, 'UM', '{"en":"Mauritanian ouguiya","ar":"أوقية موريتانية"}'),
  ('MUR', '480', 2, 'Rs', '{"en":"Mauritian rupee","ar":"روبية موريشيوسية"}'),
  ('MVR', '462', 2, 'Rf', '{"en":"Maldivian rufiyaa","ar":"روفيا مالديفية"}'),
  ('MWK', '454', 2, 'MK', '{"en":"Malawian kwacha","ar":"كواشا مالاوي"}'),
  ('MXN', '484', 2, '$', '{"en":"Mexican peso","ar":"بيزو مكسيكي"}'),
  ('MYR', '458', 2, 'RM', '{"en":"Malaysian ringgit","ar":"رينغيت ماليزي"}'),
  ('MZN', '943', 2, 'MT', '{"en":"Mozambican metical","ar":"متكال موزمبيقي"}'),
  ('NAD', '516', 2, '$', '{"en":"Namibian dollar","ar":"دولار ناميبي"}'),
  ('NGN', '566', 2, '₦', '{"en":"Nigerian naira","ar":"نيرة نيجيرية"}'),
  ('NIO', '558', 2, 'C$', '{"en":"Nicaraguan córdoba","ar":"كوردوبا نيكاراغوي"}'),
  ('NOK', '578', 2, 'kr', '{"en":"Norwegian krone","ar":"كرونة نرويجية"}'),
  ('NPR', '524', 2, 'Rs', '{"en":"Nepalese rupee","ar":"روبية نيبالية"}'),
  ('NZD', '554', 2, 'NZ$', '{"en":"New Zealand dollar","ar":"دولار نيوزيلندي"}'),
  ('OMR', '512', 3, 'ر.ع.', '{"en":"Omani rial","ar":"ريال عماني"}'),
  ('PAB', '590', 2, 'B/.', '{"en":"Panamanian balboa","ar":"بالبوا بنمي"}'),
  ('PEN', '604', 2, 'S/', '{"en":"Peruvian sol","ar":"سول بيروفي"}'),
  ('PGK', '598', 2, 'K', '{"en":"Papua New Guinean kina","ar":"كينا بابوا غينيا الجديدة"}'),
  ('PHP', '608', 2, '₱', '{"en":"Philippine peso","ar":"بيزو فلبيني"}'),
  ('PKR', '586', 2, 'Rs', '{"en":"Pakistani rupee","ar":"روبية باكستانية"}'),
  ('PLN', '985', 2, 'zł', '{"en":"Polish złoty","ar":"زلوتي بولندي"}'),
  ('PYG', '600', 0, '₲', '{"en":"Paraguayan guaraní","ar":"غواراني باراغواي"}'),
  ('QAR', '634', 2, 'ر.ق', '{"en":"Qatari riyal","ar":"ريال قطري"}'),
  ('RON', '946', 2, 'lei', '{"en":"Romanian leu","ar":"ليو روماني"}'),
  ('RSD', '941', 2, 'дин', '{"en":"Serbian dinar","ar":"دينار صربي"}'),
  ('RUB', '643', 2, '₽', '{"en":"Russian ruble","ar":"روبل روسي"}'),
  ('RWF', '646', 0, 'FRw', '{"en":"Rwandan franc","ar":"فرنك رواندي"}'),
  ('SAR', '682', 2, 'ر.س', '{"en":"Saudi riyal","ar":"ريال سعودي"}'),
  ('SBD', '090', 2, '$', '{"en":"Solomon Islands dollar","ar":"دولار جزر سليمان"}'),
  ('SCR', '690', 2, 'Rs', '{"en":"Seychellois rupee","ar":"روبية سيشيلية"}'),
  ('SDG', '938', 2, 'ج.س.', '{"en":"Sudanese pound","ar":"جنيه سوداني"}'),
  ('SEK', '752', 2, 'kr', '{"en":"Swedish krona","ar":"كرونا سويدية"}'),
  ('SGD', '702', 2, 'S$', '{"en":"Singapore dollar","ar":"دولار سنغافوري"}'),
  ('SHP', '654', 2, '£', '{"en":"Saint Helena pound","ar":"جنيه سانت هيلينا"}'),
  ('SLE', '925', 2, 'Le', '{"en":"Sierra Leonean leone","ar":"ليون سيراليوني"}'),
  ('SOS', '706', 2, 'Sh', '{"en":"Somali shilling","ar":"شلن صومالي"}'),
  ('SRD', '968', 2, '$', '{"en":"Surinamese dollar","ar":"دولار سورينامي"}'),
  ('SSP', '728', 2, '£', '{"en":"South Sudanese pound","ar":"جنيه جنوب السودان"}'),
  ('STN', '930', 2, 'Db', '{"en":"São Tomé and Príncipe dobra","ar":"دوبرا ساو تومي وبرينسيب"}'),
  ('SVC', '222', 2, '₡', '{"en":"Salvadoran colón","ar":"كولون سلفادوري"}'),
  ('SYP', '760', 2, 'ل.س', '{"en":"Syrian pound","ar":"ليرة سورية"}'),
  ('SZL', '748', 2, 'L', '{"en":"Swazi lilangeni","ar":"ليلانغيني سوازيلندي"}'),
  ('THB', '764', 2, '฿', '{"en":"Thai baht","ar":"بات تايلندي"}'),
  ('TJS', '972', 2, 'SM', '{"en":"Tajikistani somoni","ar":"سوموني طاجيكي"}'),
  ('TMT', '934', 2, 'm', '{"en":"Turkmenistan manat","ar":"مانات تركمانستاني"}'),
  ('TND', '788', 3, 'د.ت', '{"en":"Tunisian dinar","ar":"دينار تونسي"}'),
  ('TOP', '776', 2, 'T$', '{"en":"Tongan paʻanga","ar":"بانغا تونغي"}'),
  ('TRY', '949', 2, '₺', '{"en":"Turkish lira","ar":"ليرة تركية"}'),
  ('TTD', '780', 2, 'TT$', '{"en":"Trinidad and Tobago dollar","ar":"دولار ترينيداد وتوباغو"}'),
  ('TWD', '901', 2, 'NT$', '{"en":"New Taiwan dollar","ar":"دولار تايواني جديد"}'),
  ('TZS', '834', 2, 'Sh', '{"en":"Tanzanian shilling","ar":"شلن تنزاني"}'),
  ('UAH', '980', 2, '₴', '{"en":"Ukrainian hryvnia","ar":"هريفنيا أوكرانية"}'),
  ('UGX', '800', 0, 'USh', '{"en":"Ugandan shilling","ar":"شلن أوغندي"}'),
  ('USD', '840', 2, '$', '{"en":"US dollar","ar":"دولار أمريكي"}'),
  ('UYU', '858', 2, '$U', '{"en":"Uruguayan peso","ar":"بيزو أوروغواي"}'),
  ('UZS', '860', 2, 'soʻm', '{"en":"Uzbekistani soʻm","ar":"سوم أوزبكستاني"}'),
  ('VES', '928', 2, 'Bs.S', '{"en":"Venezuelan bolívar","ar":"بوليفار فنزويلي"}'),
  ('VND', '704', 0, '₫', '{"en":"Vietnamese đồng","ar":"دونغ فيتنامي"}'),
  ('VUV', '548', 0, 'VT', '{"en":"Vanuatu vatu","ar":"فاتو فانواتي"}'),
  ('WST', '882', 2, 'T', '{"en":"Samoan tālā","ar":"تالا ساموي"}'),
  ('XAF', '950', 0, 'FCFA', '{"en":"Central African CFA franc","ar":"فرنك وسط أفريقي"}'),
  ('XCD', '951', 2, '$', '{"en":"East Caribbean dollar","ar":"دولار شرق الكاريبي"}'),
  ('XOF', '952', 0, 'CFA', '{"en":"West African CFA franc","ar":"فرنك غرب أفريقي"}'),
  ('XPF', '953', 0, '₣', '{"en":"CFP franc","ar":"فرنك باسيفيكي"}'),
  ('YER', '886', 2, '﷼', '{"en":"Yemeni rial","ar":"ريال يمني"}'),
  ('ZAR', '710', 2, 'R', '{"en":"South African rand","ar":"راند جنوب أفريقي"}'),
  ('ZMW', '967', 2, 'ZK', '{"en":"Zambian kwacha","ar":"كواشا زامبي"}'),
  ('ZWG', '924', 2, 'ZiG', '{"en":"Zimbabwe gold","ar":"زيمبابوي غولد"}')
ON CONFLICT (code) DO UPDATE SET
  numeric_code = EXCLUDED.numeric_code,
  minor_units = EXCLUDED.minor_units,
  symbol = EXCLUDED.symbol,
  name_i18n = EXCLUDED.name_i18n;
