-- ISO 4217 currencies seed (idempotent, M1.6)
-- Reference implementation loads the full list; this excerpt includes major currencies and all Gulf/MENA region.

INSERT INTO control.org_currencies (code, numeric_code, minor_units, symbol, name_i18n, is_active) VALUES
('AED', '784', 2, 'د.إ', '{"en": "United Arab Emirates Dirham", "ar": "درهم إماراتي"}'::jsonb, true),
('AFN', '971', 2, '؋', '{"en": "Afghan Afghani", "ar": "الأفغاني الأفغاني"}'::jsonb, true),
('ALL', '008', 2, 'L', '{"en": "Albanian Lek", "ar": "الليك الألباني"}'::jsonb, true),
('AMD', '051', 2, '֏', '{"en": "Armenian Dram", "ar": "الدرام الأرمني"}'::jsonb, true),
('ANG', '532', 2, 'ƒ', '{"en": "Netherlands Antillean Gulden", "ar": "غيلدن جزر الأنتيل الهولندية"}'::jsonb, true),
('AOA', '024', 2, 'Kz', '{"en": "Angolan Kwanza", "ar": "الكوانزا الأنغولية"}'::jsonb, true),
('ARS', '032', 2, '$', '{"en": "Argentine Peso", "ar": "البيسو الأرجنتيني"}'::jsonb, true),
('AUD', '036', 2, '$', '{"en": "Australian Dollar", "ar": "الدولار الأسترالي"}'::jsonb, true),
('AWG', '533', 2, 'ƒ', '{"en": "Aruban Florin", "ar": "فلورين أروبا"}'::jsonb, true),
('AZN', '944', 2, '₼', '{"en": "Azerbaijani Manat", "ar": "المنات الأذربيجاني"}'::jsonb, true),
('BAM', '977', 2, 'KM', '{"en": "Bosnia and Herzegovina Convertible Mark", "ar": "علامة البوسنة والهرسك"}'::jsonb, true),
('BBD', '052', 2, '$', '{"en": "Barbadian Dollar", "ar": "دولار بربادوس"}'::jsonb, true),
('BDT', '050', 2, '৳', '{"en": "Bangladeshi Taka", "ar": "التاكا البنغلاديشية"}'::jsonb, true),
('BGN', '975', 2, 'лв', '{"en": "Bulgarian Lev", "ar": "الليف البلغاري"}'::jsonb, true),
('BHD', '048', 3, '.د.ب', '{"en": "Bahraini Dinar", "ar": "الدينار البحريني"}'::jsonb, true),
('BIF', '108', 0, 'FBu', '{"en": "Burundian Franc", "ar": "الفرنك البوروندي"}'::jsonb, true),
('BMD', '060', 2, '$', '{"en": "Bermudian Dollar", "ar": "دولار برمودا"}'::jsonb, true),
('BND', '096', 2, '$', '{"en": "Brunei Dollar", "ar": "دولار بروناي"}'::jsonb, true),
('BOB', '068', 2, 'Bs.', '{"en": "Bolivian Boliviano", "ar": "البوليفيانو البوليفي"}'::jsonb, true),
('BRL', '986', 2, 'R$', '{"en": "Brazilian Real", "ar": "الريال البرازيلي"}'::jsonb, true),
('BSD', '044', 2, '$', '{"en": "Bahamian Dollar", "ar": "دولار جزر البهاما"}'::jsonb, true),
('BTC', '0', 8, '₿', '{"en": "Bitcoin", "ar": "بيتكوين"}'::jsonb, true),
('BTN', '064', 2, 'Nu.', '{"en": "Bhutanese Ngultrum", "ar": "النغولترم البوتاني"}'::jsonb, true),
('BWP', '072', 2, 'P', '{"en": "Botswanan Pula", "ar": "البولا البوتسواني"}'::jsonb, true),
('BYN', '933', 2, 'Br', '{"en": "Belarusian Ruble", "ar": "الروبل البيلاروسي"}'::jsonb, true),
('BZD', '084', 2, '$', '{"en": "Belize Dollar", "ar": "دولار بليز"}'::jsonb, true),
('CAD', '124', 2, '$', '{"en": "Canadian Dollar", "ar": "الدولار الكندي"}'::jsonb, true),
('CDF', '976', 2, 'FC', '{"en": "Congolese Franc", "ar": "الفرنك الكونغولي"}'::jsonb, true),
('CHF', '756', 2, 'CHF', '{"en": "Swiss Franc", "ar": "الفرنك السويسري"}'::jsonb, true),
('CLF', '990', 4, 'UF', '{"en": "Chilean Unit of Account (UF)", "ar": "وحدة الحساب التشيلية"}'::jsonb, true),
('CLP', '152', 0, '$', '{"en": "Chilean Peso", "ar": "البيسو التشيلي"}'::jsonb, true),
('CNY', '156', 2, '¥', '{"en": "Chinese Yuan", "ar": "اليوان الصيني"}'::jsonb, true),
('COP', '170', 2, '$', '{"en": "Colombian Peso", "ar": "البيسو الكولومبي"}'::jsonb, true),
('CRC', '188', 2, '₡', '{"en": "Costa Rican Colón", "ar": "الكولون الكوستاريكي"}'::jsonb, true),
('CUC', '931', 2, '$', '{"en": "Cuban Convertible Peso", "ar": "البيسو الكوبي القابل للتحويل"}'::jsonb, true),
('CUP', '192', 2, '₱', '{"en": "Cuban Peso", "ar": "البيسو الكوبي"}'::jsonb, true),
('CVE', '132', 2, '$', '{"en": "Cape Verdean Escudo", "ar": "إسكودو كيب فيردي"}'::jsonb, true),
('CZK', '203', 2, 'Kč', '{"en": "Czech Koruna", "ar": "الكرونة التشيكية"}'::jsonb, true),
('DJF', '262', 0, 'Fdj', '{"en": "Djiboutian Franc", "ar": "الفرنك الجيبوتي"}'::jsonb, true),
('DKK', '208', 2, 'kr', '{"en": "Danish Krone", "ar": "الكرونة الدنماركية"}'::jsonb, true),
('DOP', '214', 2, 'RD$', '{"en": "Dominican Peso", "ar": "البيسو الدومينيكي"}'::jsonb, true),
('DZD', '012', 2, 'د.ج', '{"en": "Algerian Dinar", "ar": "الدينار الجزائري"}'::jsonb, true),
('EGP', '818', 2, '£', '{"en": "Egyptian Pound", "ar": "الجنيه المصري"}'::jsonb, true),
('ERN', '232', 2, 'Nfk', '{"en": "Eritrean Nakfa", "ar": "الناكفا الإريترية"}'::jsonb, true),
('ETB', '230', 2, 'Br', '{"en": "Ethiopian Birr", "ar": "البر الإثيوبي"}'::jsonb, true),
('EUR', '978', 2, '€', '{"en": "Euro", "ar": "اليورو"}'::jsonb, true),
('FJD', '242', 2, '$', '{"en": "Fijian Dollar", "ar": "دولار فيجي"}'::jsonb, true),
('FKP', '238', 2, '£', '{"en": "Falkland Islands Pound", "ar": "جنيه جزر فوكلاند"}'::jsonb, true),
('GBP', '826', 2, '£', '{"en": "British Pound Sterling", "ar": "الجنيه الإسترليني"}'::jsonb, true),
('GEL', '981', 2, '₾', '{"en": "Georgian Lari", "ar": "اللاري الجورجي"}'::jsonb, true),
('GHS', '288', 2, '₵', '{"en": "Ghanaian Cedi", "ar": "السيدي الغاني"}'::jsonb, true),
('GIP', '292', 2, '£', '{"en": "Gibraltar Pound", "ar": "جنيه جبل طارق"}'::jsonb, true),
('GMD', '270', 2, 'D', '{"en": "Gambian Dalasi", "ar": "الدالاسي الغامبي"}'::jsonb, true),
('GNF', '324', 0, 'FG', '{"en": "Guinean Franc", "ar": "الفرنك الغيني"}'::jsonb, true),
('GTQ', '320', 2, 'Q', '{"en": "Guatemalan Quetzal", "ar": "كيتزال غواتيمالا"}'::jsonb, true),
('GYD', '328', 2, '$', '{"en": "Guyanaese Dollar", "ar": "دولار غيانا"}'::jsonb, true),
('HKD', '344', 2, '$', '{"en": "Hong Kong Dollar", "ar": "دولار هونج كونج"}'::jsonb, true),
('HNL', '340', 2, 'L', '{"en": "Honduran Lempira", "ar": "لمبيرا هندوراس"}'::jsonb, true),
('HRK', '191', 2, 'kn', '{"en": "Croatian Kuna", "ar": "الكونا الكرواتية"}'::jsonb, true),
('HTG', '332', 2, 'G', '{"en": "Haitian Gourde", "ar": "الجورد الهايتي"}'::jsonb, true),
('HUF', '348', 2, 'Ft', '{"en": "Hungarian Forint", "ar": "الفورنت المجري"}'::jsonb, true),
('IDR', '360', 2, 'Rp', '{"en": "Indonesian Rupiah", "ar": "الروبية الإندونيسية"}'::jsonb, true),
('ILS', '376', 2, '₪', '{"en": "Israeli New Shekel", "ar": "الشيكل الإسرائيلي الجديد"}'::jsonb, true),
('INR', '356', 2, '₹', '{"en": "Indian Rupee", "ar": "روبية هندية"}'::jsonb, true),
('IQD', '368', 3, 'ع.د', '{"en": "Iraqi Dinar", "ar": "الدينار العراقي"}'::jsonb, true),
('IRR', '364', 2, '﷼', '{"en": "Iranian Rial", "ar": "الريال الإيراني"}'::jsonb, true),
('ISK', '352', 0, 'kr', '{"en": "Icelandic Króna", "ar": "الكرونا الأيسلندية"}'::jsonb, true),
('JMD', '388', 2, '$', '{"en": "Jamaican Dollar", "ar": "دولار جامايكا"}'::jsonb, true),
('JOD', '400', 3, 'د.ا', '{"en": "Jordanian Dinar", "ar": "الدينار الأردني"}'::jsonb, true),
('JPY', '392', 0, '¥', '{"en": "Japanese Yen", "ar": "الين الياباني"}'::jsonb, true),
('KES', '404', 2, 'Sh', '{"en": "Kenyan Shilling", "ar": "الشلن الكيني"}'::jsonb, true),
('KGS', '417', 2, 'с', '{"en": "Kyrgyzstani Som", "ar": "الصوم القيرغيزستاني"}'::jsonb, true),
('KHR', '116', 2, '៛', '{"en": "Cambodian Riel", "ar": "الريل الكمبودي"}'::jsonb, true),
('KMF', '174', 0, 'CF', '{"en": "Comorian Franc", "ar": "الفرنك القمري"}'::jsonb, true),
('KPW', '408', 2, '₩', '{"en": "North Korean Won", "ar": "الون الكوري الشمالي"}'::jsonb, true),
('KRW', '410', 0, '₩', '{"en": "South Korean Won", "ar": "الون الكوري الجنوبي"}'::jsonb, true),
('KWD', '414', 3, 'د.ك', '{"en": "Kuwaiti Dinar", "ar": "الدينار الكويتي"}'::jsonb, true),
('KYD', '136', 2, '$', '{"en": "Cayman Islands Dollar", "ar": "دولار جزر كايمان"}'::jsonb, true),
('KZT', '398', 2, '₸', '{"en": "Kazakhstani Tenge", "ar": "التنغة الكازاخستانية"}'::jsonb, true),
('LAK', '418', 2, '₭', '{"en": "Laotian Kip", "ar": "كيب لاوس"}'::jsonb, true),
('LBP', '422', 2, '£', '{"en": "Lebanese Pound", "ar": "الجنيه اللبناني"}'::jsonb, true),
('LKR', '144', 2, 'Rs', '{"en": "Sri Lankan Rupee", "ar": "روبية سريلانكا"}'::jsonb, true),
('LRD', '430', 2, '$', '{"en": "Liberian Dollar", "ar": "دولار ليبيريا"}'::jsonb, true),
('LSL', '426', 2, 'L', '{"en": "Lesotho Loti", "ar": "اللوتي اللسوتو"}'::jsonb, true),
('LYD', '434', 3, 'ل.د', '{"en": "Libyan Dinar", "ar": "الدينار الليبي"}'::jsonb, true),
('MAD', '504', 2, 'د.م.', '{"en": "Moroccan Dirham", "ar": "الدرهم المغربي"}'::jsonb, true),
('MDL', '498', 2, 'L', '{"en": "Moldovan Leu", "ar": "الليو المولدوفي"}'::jsonb, true),
('MGA', '969', 2, 'Ar', '{"en": "Malagasy Ariary", "ar": "الأرياري الملغاشي"}'::jsonb, true),
('MKD', '807', 2, 'ден', '{"en": "Macedonian Denar", "ar": "الدينار المقدوني"}'::jsonb, true),
('MMK', '104', 2, 'K', '{"en": "Myanma Kyat", "ar": "الكيات الميانمارية"}'::jsonb, true),
('MNT', '496', 2, '₮', '{"en": "Mongolian Tugrik", "ar": "التوجريك المنغولي"}'::jsonb, true),
('MOP', '446', 2, 'P', '{"en": "Macanese Pataca", "ar": "الباتاكا الماكاوية"}'::jsonb, true),
('MRU', '929', 2, 'UM', '{"en": "Mauritanian Ouguiya", "ar": "الأوقية الموريتانية"}'::jsonb, true),
('MUR', '480', 2, '₨', '{"en": "Mauritian Rupee", "ar": "روبية موريشيوس"}'::jsonb, true),
('MVR', '462', 2, 'Rf', '{"en": "Maldivian Rufiyaa", "ar": "الروفية المالديفية"}'::jsonb, true),
('MWK', '454', 2, 'MK', '{"en": "Malawian Kwacha", "ar": "الكواشا الملاوية"}'::jsonb, true),
('MXN', '484', 2, '$', '{"en": "Mexican Peso", "ar": "البيسو المكسيكي"}'::jsonb, true),
('MYR', '458', 2, 'RM', '{"en": "Malaysian Ringgit", "ar": "الرينغيت الماليزي"}'::jsonb, true),
('MZN', '943', 2, 'MT', '{"en": "Mozambican Metical", "ar": "المتيكال الموزمبيقي"}'::jsonb, true),
('NAD', '516', 2, '$', '{"en": "Namibian Dollar", "ar": "دولار ناميبيا"}'::jsonb, true),
('NGN', '566', 2, '₦', '{"en": "Nigerian Naira", "ar": "النيرة النيجيرية"}'::jsonb, true),
('NIO', '558', 2, 'C$', '{"en": "Nicaraguan Córdoba", "ar": "كوردوبا نيكاراغوا"}'::jsonb, true),
('NOK', '578', 2, 'kr', '{"en": "Norwegian Krone", "ar": "الكرونة النرويجية"}'::jsonb, true),
('NPR', '524', 2, '₨', '{"en": "Nepalese Rupee", "ar": "روبية نيبالية"}'::jsonb, true),
('NZD', '554', 2, '$', '{"en": "New Zealand Dollar", "ar": "دولار نيوزيلندا"}'::jsonb, true),
('OMR', '512', 3, 'ر.ع.', '{"en": "Omani Rial", "ar": "الريال العماني"}'::jsonb, true),
('PAB', '590', 2, 'B/.', '{"en": "Panamanian Balboa", "ar": "بالبوا بنما"}'::jsonb, true),
('PEN', '604', 2, 'S/.', '{"en": "Peruvian Sol", "ar": "سول بيرو"}'::jsonb, true),
('PGK', '598', 2, 'K', '{"en": "Papua New Guinean Kina", "ar": "الكينا الباپوية"}'::jsonb, true),
('PHP', '608', 2, '₱', '{"en": "Philippine Peso", "ar": "البيسو الفيليبيني"}'::jsonb, true),
('PKR', '586', 2, '₨', '{"en": "Pakistani Rupee", "ar": "روبية باكستانية"}'::jsonb, true),
('PLN', '616', 2, 'zł', '{"en": "Polish Zloty", "ar": "الزلوتي البولندي"}'::jsonb, true),
('PYG', '600', 0, '₲', '{"en": "Paraguayan Guaraní", "ar": "جواراني باراغواي"}'::jsonb, true),
('QAR', '634', 2, 'ر.ق', '{"en": "Qatari Riyal", "ar": "الريال القطري"}'::jsonb, true),
('RON', '946', 2, 'lei', '{"en": "Romanian Leu", "ar": "الليو الروماني"}'::jsonb, true),
('RSD', '941', 2, 'Дин.', '{"en": "Serbian Dinar", "ar": "الدينار الصربي"}'::jsonb, true),
('RUB', '643', 2, '₽', '{"en": "Russian Ruble", "ar": "الروبل الروسي"}'::jsonb, true),
('RWF', '646', 0, 'Fr', '{"en": "Rwandan Franc", "ar": "الفرنك الرواندي"}'::jsonb, true),
('SAR', '682', 2, 'ر.س', '{"en": "Saudi Arabian Riyal", "ar": "الريال السعودي"}'::jsonb, true),
('SBD', '090', 2, '$', '{"en": "Solomon Islands Dollar", "ar": "دولار جزر سليمان"}'::jsonb, true),
('SCR', '690', 2, '₨', '{"en": "Seychellois Rupee", "ar": "روبية سيشل"}'::jsonb, true),
('SDG', '938', 2, 'ج.س.', '{"en": "Sudanese Pound", "ar": "الجنيه السوداني"}'::jsonb, true),
('SEK', '752', 2, 'kr', '{"en": "Swedish Krona", "ar": "الكرونة السويدية"}'::jsonb, true),
('SGD', '702', 2, '$', '{"en": "Singapore Dollar", "ar": "دولار سنغافورة"}'::jsonb, true),
('SHP', '654', 2, '£', '{"en": "Saint Helena Pound", "ar": "جنيه سانت هيلينا"}'::jsonb, true),
('SLL', '694', 2, 'Le', '{"en": "Sierra Leonean Leone", "ar": "ليون سيراليون"}'::jsonb, true),
('SOS', '706', 2, 'Sh', '{"en": "Somali Shilling", "ar": "الشلن الصومالي"}'::jsonb, true),
('SRD', '740', 2, '$', '{"en": "Surinamese Dollar", "ar": "دولار سورينام"}'::jsonb, true),
('STN', '930', 2, 'Db', '{"en": "São Tomé and Príncipe Dobra", "ar": "دوبرا ساو تومي وبرينسيبي"}'::jsonb, true),
('SYP', '760', 2, '£', '{"en": "Syrian Pound", "ar": "الجنيه السوري"}'::jsonb, true),
('SZL', '748', 2, 'E', '{"en": "Swazi Lilangeni", "ar": "الليلانغيني السوازي"}'::jsonb, true),
('THB', '764', 2, '฿', '{"en": "Thai Baht", "ar": "بات تايلاند"}'::jsonb, true),
('TJS', '762', 2, 'ЅМ', '{"en": "Tajikistani Somoni", "ar": "السوموني الطاجيكي"}'::jsonb, true),
('TMT', '795', 2, 'm', '{"en": "Turkmenistan Manat", "ar": "المنات التركمانستاني"}'::jsonb, true),
('TND', '788', 3, 'د.ت', '{"en": "Tunisian Dinar", "ar": "الدينار التونسي"}'::jsonb, true),
('TOP', '776', 2, 'T$', '{"en": "Tongan Paʻanga", "ar": "بانغا تونغا"}'::jsonb, true),
('TRY', '949', 2, '₺', '{"en": "Turkish Lira", "ar": "الليرة التركية"}'::jsonb, true),
('TTD', '780', 2, '$', '{"en": "Trinidad and Tobago Dollar", "ar": "دولار ترينيداد وتوباغو"}'::jsonb, true),
('TWD', '901', 2, 'NT$', '{"en": "New Taiwan Dollar", "ar": "دولار تايوان الجديد"}'::jsonb, true),
('TZS', '834', 2, 'Sh', '{"en": "Tanzanian Shilling", "ar": "الشلن التنزاني"}'::jsonb, true),
('UAH', '980', 2, '₴', '{"en": "Ukrainian Hryvnia", "ar": "الهريفنيا الأوكرانية"}'::jsonb, true),
('UGX', '800', 0, 'Sh', '{"en": "Ugandan Shilling", "ar": "الشلن الأوغندي"}'::jsonb, true),
('USD', '840', 2, '$', '{"en": "United States Dollar", "ar": "دولار أمريكي"}'::jsonb, true),
('UYU', '858', 2, '$', '{"en": "Uruguayan Peso", "ar": "البيسو الأوروغواي"}'::jsonb, true),
('UZS', '860', 2, 'сўм', '{"en": "Uzbekistani Som", "ar": "الصوم الأوزبكي"}'::jsonb, true),
('VED', '926', 2, 'Bs.', '{"en": "Venezuelan Bolívars (Digital)", "ar": "البوليفار الفنزويلي"}'::jsonb, true),
('VES', '928', 2, 'Bs.', '{"en": "Venezuelan Bolívar Soberano", "ar": "البوليفار السيادي الفنزويلي"}'::jsonb, true),
('VND', '704', 0, '₫', '{"en": "Vietnamese Đồng", "ar": "دونج فيتنام"}'::jsonb, true),
('VUV', '548', 0, 'Vt', '{"en": "Vanuatu Vatu", "ar": "فاتو فانواتو"}'::jsonb, true),
('WST', '882', 2, 'T', '{"en": "Samoan Tala", "ar": "تالا ساموا"}'::jsonb, true),
('XAF', '950', 0, 'FCFA', '{"en": "Central African CFA Franc", "ar": "فرنك وسط أفريقيا"}'::jsonb, true),
('XCD', '951', 2, '$', '{"en": "East Caribbean Dollar", "ar": "دولار الكاريبي الشرقي"}'::jsonb, true),
('XOF', '952', 0, 'CFA', '{"en": "West African CFA Franc", "ar": "فرنك غرب أفريقيا"}'::jsonb, true),
('XPF', '953', 0, '₣', '{"en": "CFP Franc", "ar": "فرنك المحيط الهادئ"}'::jsonb, true),
('YER', '886', 2, '﷼', '{"en": "Yemeni Rial", "ar": "الريال اليمني"}'::jsonb, true),
('ZAR', '710', 2, 'R', '{"en": "South African Rand", "ar": "الراند الجنوب أفريقي"}'::jsonb, true),
('ZMW', '967', 2, 'ZK', '{"en": "Zambian Kwacha", "ar": "الكواشا الزامبية"}'::jsonb, true),
('ZWL', '932', 2, 'Z$', '{"en": "Zimbabwean Dollar", "ar": "دولار زيمبابوي"}'::jsonb, true)
ON CONFLICT (code) DO NOTHING;
