<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../Quicker.Items.TestSupport/Quicker.Items.TestSupport.csproj" />
    <ProjectReference Include="../Quicker.Items/Quicker.Items.csproj" />
    <ProjectReference Include="../../Identity/Quicker.Identity.TestSupport/Quicker.Identity.TestSupport.csproj" />
  </ItemGroup>
</Project>
